#!/usr/bin/env bash
#
#/ command: nexus:status: "obtain status of the nexus service"
#
#/ usage: rerun nexus:status [options]
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: 

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/status/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/status/options.sh || rerun_die "Failed loading options parser."
}


# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die "*** command failed: nexus:status. ***"' ERR
set -o nounset -o pipefail


# ------------------------------
# Your implementation goes here.
# ------------------------------
sudo service nexus status

exit $?

# Done
